force-app/main/default/objects/Account/fields/Approved_Funding__c.field-meta.xml
<CustomField>
    <fullName>Approved_Funding__c</fullName>
    <description>Amount of funding approved during the negotiation stage for a funding opportunity.</description>
    <label>Approved Funding</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Budget_Share__c.field-meta.xml
<CustomField>
    <fullName>Budget_Share__c</fullName>
    <description>The amount of budget responsibility the company will take on.</description>
    <label>Budget Share</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Account/fields/Contract_Length__c.field-meta.xml
<CustomField>
    <fullName>Contract_Length__c</fullName>
    <description>Contract length, in months, for small business program.</description>
    <inlineHelpText>Number of months the assigned funding will last</inlineHelpText>
    <label>Contract Length</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Enrollment_Date__c.field-meta.xml
<CustomField>
    <fullName>Enrollment_Date__c</fullName>
    <description>When the company was enrolled into the program</description>
    <inlineHelpText>When the company got accepted within the program</inlineHelpText>
    <label>Enrollment Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Funding_Opportunity_del__c.field-meta.xml
<CustomField>
    <fullName>Funding_Opportunity_del__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Funding Opportunity assigned to the account.</description>
    <label>Funding Opportunity</label>
    <referenceTo>Funding_Opportunity__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts_del</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/NAICS_Code__c.field-meta.xml
<CustomField>
    <fullName>NAICS_Code__c</fullName>
    <label>NAICS Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>NAICS_Codes</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <description>Region of the account</description>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Regions</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <description>State of the account.</description>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Region__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>States</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Time_In_Program__c.field-meta.xml
<CustomField>
    <fullName>Time_In_Program__c</fullName>
    <description>Days since the company has enrolled in the program</description>
    <formula>TEXT(TODAY() - Enrollment_Date__c) + &quot; Days&quot;</formula>
    <inlineHelpText>Days since the company has enrolled in the program</inlineHelpText>
    <label>Time In Program</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Funding_Opportunity__c/Funding_Opportunity__c.object-meta.xml
<CustomObject>
    <description>Grants available within the EERE Small Business Program</description>
    <label>Funding Opportunity</label>
    <nameField>
        <displayFormat>DE-FOA-{00000000}</displayFormat>
        <label>Funding Opportunity</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Funding Opportunities</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Funding_Opportunity__c/fields/NAICS_Code__c.field-meta.xml
<CustomField>
    <fullName>NAICS_Code__c</fullName>
    <description>NAICS code associated with the grant</description>
    <label>NAICS Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>NAICS_Codes</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Funding_Opportunity__c/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <description>Region designation for the grant</description>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Regions</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Funding_Opportunity__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <description>State designation for the grant</description>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Region__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>States</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/NAICS_Codes.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>541611 - Administrative &amp; General Management Consulting</fullName>
        <default>true</default>
        <label>541611 - Administrative &amp; General Management Consulting</label>
    </customValue>
    <customValue>
        <fullName>541690 - Other Scientific &amp; Technical Consulting</fullName>
    </customValue>
    <customValue>
        <fullName>541330 - Engineering Services</fullName>
    </customValue>
    <customValue>
        <fullName>561210 - Facilities Support Service</fullName>
    </customValue>
    <customValue>
        <fullName>541820 - Public Relations Agencies</fullName>
    </customValue>
    <customValue>
        <fullName>541512 - Computer System Design Services</fullName>
    </customValue>
    <customValue>
        <fullName>541519 - Other Computer Related Services</fullName>
    </customValue>
    <customValue>
        <fullName>519130 - Internet Publishing, Broadcasting, Web Search Portals</fullName>
    </customValue>
    <customValue>
        <fullName>541618 - Other Management Consulting Services</fullName>
    </customValue>
    <customValue>
        <fullName>333316 - Photographic &amp; Photocopying Equipment Manufacturing</fullName>
    </customValue>
    <description>NAICS codes</description>
    <masterLabel>NAICS Codes</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Regions.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Great Lakes</fullName>
    </customValue>
    <customValue>
        <fullName>Northeast</fullName>
    </customValue>
    <customValue>
        <fullName>Pacific</fullName>
    </customValue>
    <customValue>
        <fullName>Southern</fullName>
    </customValue>
    <customValue>
        <fullName>Western</fullName>
    </customValue>
    <description>Regions for departments</description>
    <masterLabel>Regions</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/States.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Illinois</fullName>
    </customValue>
    <customValue>
        <fullName>Indiana</fullName>
    </customValue>
    <customValue>
        <fullName>Iowa</fullName>
    </customValue>
    <customValue>
        <fullName>Michigan</fullName>
    </customValue>
    <customValue>
        <fullName>Minnesota</fullName>
    </customValue>
    <customValue>
        <fullName>Ohio</fullName>
    </customValue>
    <customValue>
        <fullName>Wisconsin</fullName>
    </customValue>
    <customValue>
        <fullName>Connecticut</fullName>
    </customValue>
    <customValue>
        <fullName>Delaware</fullName>
    </customValue>
    <customValue>
        <fullName>Maine</fullName>
    </customValue>
    <customValue>
        <fullName>Maryland</fullName>
    </customValue>
    <customValue>
        <fullName>Massachusetts</fullName>
    </customValue>
    <customValue>
        <fullName>New Hampshire</fullName>
    </customValue>
    <customValue>
        <fullName>New Jersey</fullName>
    </customValue>
    <customValue>
        <fullName>New York</fullName>
    </customValue>
    <customValue>
        <fullName>Pennsylvania</fullName>
    </customValue>
    <customValue>
        <fullName>Rhode Island</fullName>
    </customValue>
    <customValue>
        <fullName>Vermont</fullName>
    </customValue>
    <customValue>
        <fullName>Alaska</fullName>
    </customValue>
    <customValue>
        <fullName>Hawaii</fullName>
    </customValue>
    <customValue>
        <fullName>Idaho</fullName>
    </customValue>
    <customValue>
        <fullName>Oregon</fullName>
    </customValue>
    <customValue>
        <fullName>Montana</fullName>
    </customValue>
    <customValue>
        <fullName>Washington</fullName>
    </customValue>
    <customValue>
        <fullName>Alabama</fullName>
    </customValue>
    <customValue>
        <fullName>Arkansas</fullName>
    </customValue>
    <customValue>
        <fullName>District of Columbia</fullName>
    </customValue>
    <customValue>
        <fullName>Florida</fullName>
    </customValue>
    <customValue>
        <fullName>Georgia</fullName>
    </customValue>
    <customValue>
        <fullName>Kentucky</fullName>
    </customValue>
    <masterLabel>States</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/PartnerAccountInformationController.cls
public without sharing class PartnerAccountInformationController {
    
    @AuraEnabled(cacheable=true)
    public static Account getPartnerAccountInformation(Id userId) {
        List<User> users = [SELECT AccountId FROM User WHERE Id = :userId];
        if (users.size() == 0) {
            return null;
        }

        List<Account> accounts = new List<Account>();
        accounts = [SELECT Name, Phone, NAICS_Code__c, NumberOfEmployees, AnnualRevenue, Time_In_Program__c, 
                            Budget_Share__c, Active__c, Funding_Opportunity_del__r.Name, Region__c, Approved_Funding__c,
                            State__c, Contract_Length__c, Enrollment_Date__c
                    FROM Account
                    WHERE Id = :users[0].AccountId];
        if (accounts.size() > 0) {
            return accounts[0];
        }
        return null;
    }
}