force-app/main/default/objects/Account/fields/Budget_Share__c.field-meta.xml
<CustomField>
    <fullName>Budget_Share__c</fullName>
    <description>The amount of budget responsibility the company will take on.</description>
    <label>Budget Share</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Account/fields/Contract_Length__c.field-meta.xml
<CustomField>
    <fullName>Contract_Length__c</fullName>
    <description>Contract length, in months, for small business program.</description>
    <inlineHelpText>Number of months the assigned funding will last</inlineHelpText>
    <label>Contract Length</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Enrollment_Date__c.field-meta.xml
<CustomField>
    <fullName>Enrollment_Date__c</fullName>
    <description>When the company was enrolled into the program</description>
    <inlineHelpText>When the company got accepted within the program</inlineHelpText>
    <label>Enrollment Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/NAICS_Code__c.field-meta.xml
<CustomField>
    <fullName>NAICS_Code__c</fullName>
    <label>NAICS Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>NAICS_Codes</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <description>Region of the account</description>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Regions</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <description>State of the account.</description>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Region__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>States</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Time_In_Program__c.field-meta.xml
<CustomField>
    <fullName>Time_In_Program__c</fullName>
    <description>Days since the company has enrolled in the program</description>
    <formula>TEXT(TODAY() - Enrollment_Date__c) + &quot; Days&quot;</formula>
    <inlineHelpText>Days since the company has enrolled in the program</inlineHelpText>
    <label>Time In Program</label>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/NAICS_Codes.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>541611 - Administrative &amp; General Management Consulting</fullName>
        <default>true</default>
        <label>541611 - Administrative &amp; General Management Consulting</label>
    </customValue>
    <customValue>
        <fullName>541690 - Other Scientific &amp; Technical Consulting</fullName>
    </customValue>
    <customValue>
        <fullName>541330 - Engineering Services</fullName>
    </customValue>
    <customValue>
        <fullName>561210 - Facilities Support Service</fullName>
    </customValue>
    <customValue>
        <fullName>541820 - Public Relations Agencies</fullName>
    </customValue>
    <customValue>
        <fullName>541512 - Computer System Design Services</fullName>
    </customValue>
    <customValue>
        <fullName>541519 - Other Computer Related Services</fullName>
    </customValue>
    <customValue>
        <fullName>519130 - Internet Publishing, Broadcasting, Web Search Portals</fullName>
    </customValue>
    <customValue>
        <fullName>541618 - Other Management Consulting Services</fullName>
    </customValue>
    <customValue>
        <fullName>333316 - Photographic &amp; Photocopying Equipment Manufacturing</fullName>
    </customValue>
    <description>NAICS codes</description>
    <masterLabel>NAICS Codes</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Regions.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Great Lakes</fullName>
    </customValue>
    <customValue>
        <fullName>Northeast</fullName>
    </customValue>
    <customValue>
        <fullName>Pacific</fullName>
    </customValue>
    <customValue>
        <fullName>Southern</fullName>
    </customValue>
    <customValue>
        <fullName>Western</fullName>
    </customValue>
    <description>Regions for departments</description>
    <masterLabel>Regions</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/States.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Illinois</fullName>
    </customValue>
    <customValue>
        <fullName>Indiana</fullName>
    </customValue>
    <customValue>
        <fullName>Iowa</fullName>
    </customValue>
    <customValue>
        <fullName>Michigan</fullName>
    </customValue>
    <customValue>
        <fullName>Minnesota</fullName>
    </customValue>
    <customValue>
        <fullName>Ohio</fullName>
    </customValue>
    <customValue>
        <fullName>Wisconsin</fullName>
    </customValue>
    <customValue>
        <fullName>Connecticut</fullName>
    </customValue>
    <customValue>
        <fullName>Delaware</fullName>
    </customValue>
    <customValue>
        <fullName>Maine</fullName>
    </customValue>
    <customValue>
        <fullName>Maryland</fullName>
    </customValue>
    <customValue>
        <fullName>Massachusetts</fullName>
    </customValue>
    <customValue>
        <fullName>New Hampshire</fullName>
    </customValue>
    <customValue>
        <fullName>New Jersey</fullName>
    </customValue>
    <customValue>
        <fullName>New York</fullName>
    </customValue>
    <customValue>
        <fullName>Pennsylvania</fullName>
    </customValue>
    <customValue>
        <fullName>Rhode Island</fullName>
    </customValue>
    <customValue>
        <fullName>Vermont</fullName>
    </customValue>
    <customValue>
        <fullName>Alaska</fullName>
    </customValue>
    <customValue>
        <fullName>Hawaii</fullName>
    </customValue>
    <customValue>
        <fullName>Idaho</fullName>
    </customValue>
    <customValue>
        <fullName>Oregon</fullName>
    </customValue>
    <customValue>
        <fullName>Montana</fullName>
    </customValue>
    <customValue>
        <fullName>Washington</fullName>
    </customValue>
    <customValue>
        <fullName>Alabama</fullName>
    </customValue>
    <customValue>
        <fullName>Arkansas</fullName>
    </customValue>
    <customValue>
        <fullName>District of Columbia</fullName>
    </customValue>
    <customValue>
        <fullName>Florida</fullName>
    </customValue>
    <customValue>
        <fullName>Georgia</fullName>
    </customValue>
    <customValue>
        <fullName>Kentucky</fullName>
    </customValue>
    <masterLabel>States</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/PartnerAccountInformationController_Test.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an org are executed whenever Apex code is deployed
 * to a production org to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production org. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the org size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class PartnerAccountInformationController_Test {

    @TestSetup
    static void makeData(){
        // Create an Account
    Account acc = new Account();
    acc.Name = 'Test Account';
    acc.Phone = '123-456-7890';
    acc.NAICS_Code__c = '541611 - Administrative & General Management Consulting';
    acc.NumberOfEmployees = 1500;
    acc.AnnualRevenue = 1000000;
    acc.Budget_Share__c = 40;
    acc.Active__c = 'true';
    acc.Region__c = 'Great Lakes';
    acc.State__c = 'Illinois';
    acc.Contract_Length__c = 12;
    acc.Enrollment_Date__c = Date.today();
    insert acc;

    Contact contact = new Contact(LastName = 'Test', AccountId = acc.Id);
    insert contact;

    User user = new User(ContactId = contact.Id);
    user.Username = 'testuser' + System.currentTimeMillis() + '@test.com';
    user.Email = 'testuser@test.com';
    user.LastName = 'Test';
    user.FirstName = 'User';
    user.Alias = 'tuser';
    user.ProfileId = [SELECT Id FROM Profile WHERE Name='EERE Small Business Site User' LIMIT 1].Id;
    user.TimeZoneSidKey = 'America/Los_Angeles';
    user.LocaleSidKey = 'en_US';
    user.EmailEncodingKey = 'UTF-8';
    user.LanguageLocaleKey = 'en_US';
    insert user;
    }




    @isTest
    static void getAccountInformation() {
        User user = [SELECT Id FROM User WHERE Profile.Name = 'EERE Small Business Site User' LIMIT 1];
        Account account = PartnerAccountInformationController.getPartnerAccountInformation(user.Id);
        Assert.isNotNull(account);
        Assert.areEqual('Test Account', account.Name);
        Assert.areEqual('123-456-7890', account.Phone);
        Assert.areEqual('541611 - Administrative & General Management Consulting', account.NAICS_Code__c);
        Assert.areEqual(1500, account.NumberOfEmployees);
        Assert.areEqual(1000000, account.AnnualRevenue);
        Assert.areEqual('0 Days', account.Time_In_Program__c);
        Assert.areEqual(40, account.Budget_Share__c);
        Assert.areEqual('true', account.Active__c);
        Assert.areEqual('Great Lakes', account.Region__c);
        Assert.areEqual('Illinois', account.State__c);
        Assert.areEqual(12, account.Contract_Length__c);
        Assert.areEqual(Date.today(), account.Enrollment_Date__c);
    }

    @isTest
    static void getAccountInformationNoUser() {
        Account account = PartnerAccountInformationController.getPartnerAccountInformation(null);
        Assert.areEqual(null, account);
    }

    @isTest
    static void getAccountInformationNoAccount() {
        User user = [SELECT Id FROM User WHERE Profile.Name = 'System Administrator' LIMIT 1];
        Account account = PartnerAccountInformationController.getPartnerAccountInformation(user.Id);
        Assert.areEqual(null, account);
    }
}