force-app/main/default/objects/Lead/fields/Budget_Share__c.field-meta.xml
<CustomField>
    <fullName>Budget_Share__c</fullName>
    <description>The amount of budget responsibility the business will take on</description>
    <label>Budget Share</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Regions</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Region__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>States</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Regions.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Great Lakes</fullName>
    </customValue>
    <customValue>
        <fullName>Northeast</fullName>
    </customValue>
    <customValue>
        <fullName>Pacific</fullName>
    </customValue>
    <customValue>
        <fullName>Southern</fullName>
    </customValue>
    <customValue>
        <fullName>Western</fullName>
    </customValue>
    <description>Regions for departments</description>
    <masterLabel>Regions</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/States.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Illinois</fullName>
    </customValue>
    <customValue>
        <fullName>Indiana</fullName>
    </customValue>
    <customValue>
        <fullName>Iowa</fullName>
    </customValue>
    <customValue>
        <fullName>Michigan</fullName>
    </customValue>
    <customValue>
        <fullName>Minnesota</fullName>
    </customValue>
    <customValue>
        <fullName>Ohio</fullName>
    </customValue>
    <customValue>
        <fullName>Wisconsin</fullName>
    </customValue>
    <customValue>
        <fullName>Connecticut</fullName>
    </customValue>
    <customValue>
        <fullName>Delaware</fullName>
    </customValue>
    <customValue>
        <fullName>Maine</fullName>
    </customValue>
    <customValue>
        <fullName>Maryland</fullName>
    </customValue>
    <customValue>
        <fullName>Massachusetts</fullName>
    </customValue>
    <customValue>
        <fullName>New Hampshire</fullName>
    </customValue>
    <customValue>
        <fullName>New Jersey</fullName>
    </customValue>
    <customValue>
        <fullName>New York</fullName>
    </customValue>
    <customValue>
        <fullName>Pennsylvania</fullName>
    </customValue>
    <customValue>
        <fullName>Rhode Island</fullName>
    </customValue>
    <customValue>
        <fullName>Vermont</fullName>
    </customValue>
    <customValue>
        <fullName>Alaska</fullName>
    </customValue>
    <customValue>
        <fullName>Hawaii</fullName>
    </customValue>
    <customValue>
        <fullName>Idaho</fullName>
    </customValue>
    <customValue>
        <fullName>Oregon</fullName>
    </customValue>
    <customValue>
        <fullName>Montana</fullName>
    </customValue>
    <customValue>
        <fullName>Washington</fullName>
    </customValue>
    <customValue>
        <fullName>Alabama</fullName>
    </customValue>
    <customValue>
        <fullName>Arkansas</fullName>
    </customValue>
    <customValue>
        <fullName>District of Columbia</fullName>
    </customValue>
    <customValue>
        <fullName>Florida</fullName>
    </customValue>
    <customValue>
        <fullName>Georgia</fullName>
    </customValue>
    <customValue>
        <fullName>Kentucky</fullName>
    </customValue>
    <masterLabel>States</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/applicantSearchController.cls
public without sharing class applicantSearchController {

    @AuraEnabled(cacheable=true)
    public static Lead getApplicantLead(String lastName, string email) {
        List<Lead> lead = [SELECT Id, Name, Region__c, State__c, Email, Budget_Share__c, NumberOfEmployees, Status
                    FROM Lead
                    WHERE LastName = :lastName AND Email = :email LIMIT 1];
        if(lead.size() > 0) {
            return lead[0];
        } else {
            throw new AuraHandledException('No lead found with the given details');
        }
    }   

    @AuraEnabled(cacheable=true)
    public static List<String> getStatusValues() {
        List<String> statusValues = new List<String>();
        List<String> filterValues = new List<String>{
            'Open - Not Contacted',
            'Working - Contacted',
            'Closed - Converted',
            'Closed - Not Converted'
        };
        Schema.DescribeFieldResult fieldResult = Lead.Status.getDescribe();
        List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
        for( Schema.PicklistEntry pickListVal : ple) {
            if(filterValues.contains(pickListVal.getLabel()))
            {
                continue;
            }
            statusValues.add(pickListVal.getLabel());
        }
        return statusValues;
    }
}