force-app/main/default/objects/Contact/fields/Access_Code__c.field-meta.xml
<CustomField>
    <fullName>Access_Code__c</fullName>
    <description>Holds an accounts access code</description>
    <label>Access Code</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Funding_Opportunity__c/Funding_Opportunity__c.object-meta.xml
<CustomObject>
    <description>Grants available within the EERE Small Business Program</description>
    <label>Funding Opportunity</label>
    <nameField>
        <displayFormat>DE-FOA-{00000000}</displayFormat>
        <label>Funding Opportunity</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Funding Opportunities</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Funding_Opportunity__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>The type of funding opportunity</description>
    <label>Type</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Approved_Funding__c.field-meta.xml
<CustomField>
    <fullName>Approved_Funding__c</fullName>
    <description>Amount of funding approved during negotiations</description>
    <label>Approved Funding</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Funding_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Funding_Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Funding Opportunity the lead is applying for.</description>
    <label>Funding Opportunity</label>
    <referenceTo>Funding_Opportunity__c</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Applicants</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ContactTriggerHandler_Test.cls
@isTest
private class ContactTriggerHandler_Test {

    @isTest
    static void testAccountTriggerAccessCode() {
        // Create test data
        Lead testLead = new Lead(FirstName = 'First', LastName = 'Test', Company = 'Test Company', Email = 'mahoco2261@morxin.com', Approved_Funding__c = 1000000);
        Funding_Opportunity__c testFundingOpportunity = new Funding_Opportunity__c(Type__c = 'Test Funding Opportunity');
        insert testFundingOpportunity;
        testLead.Funding_Opportunity__c = testFundingOpportunity.Id;
        insert testLead;
        // convert lead
        Database.LeadConvert lc = new database.LeadConvert();
        lc.setLeadId(testLead.Id);
        lc.setConvertedStatus('Project Performance');
        
        // Call the trigger
        Test.startTest();
        Database.LeadConvertResult lcr = Database.convertLead(lc);
        Assert.isTrue(lcr.isSuccess());
        Test.stopTest();
        Contact contact = [SELECT Id, FirstName, LastName, Email, Access_Code__c FROM Contact WHERE Id = :lcr.getContactId()];
        Assert.areEqual('First', contact.FirstName);
        Assert.isTrue(contact.Access_Code__c != null);
    }
}
    